export const allUsers = [
  { id: "1", name: "John Doe", initials: "JD", role: "Dev" },
  { id: "2", name: "Sarah Chen", initials: "SC", role: "Dev" },
  { id: "3", name: "Mike Johnson", initials: "MJ", role: "Dev" },
  { id: "4", name: "Alex Kumar", initials: "AK", role: "Dev" },
  { id: "5", name: "Emily Davis", initials: "ED", role: "Dev" },
  { id: "6", name: "Tom Wilson", initials: "TW", role: "Dev" },
  { id: "7", name: "Lisa Park", initials: "LP", role: "Dev"},
];

export const dummyIssues = [
  {
    id: "1",
    issueNumber: 512,
    title: "Login button not responsive on mobile devices",
    description: "The login button doesn't respond to touch events on iOS Safari...",
    status: "open",
    priority: "High",
    category: "ui",
    assignedTo: [allUsers[0], allUsers[1]],
    createdBy: allUsers[2],
    createdAt: new Date("2025-11-08T10:30:00"),
    updatedAt: new Date("2025-11-09T14:20:00"),
    deadline: new Date("2025-11-15T00:00:00"),
    commentCount: 5,
    imageCount: 2,
  },
  {
    id: "2",
    issueNumber: 513,
    title: "Character animation glitch during combat",
    description: "Character model clips through the ground when performing special attack...",
    status: "pending_approval",
    priority: "medium",
    category: "dev",
    assignedTo: [allUsers[3]],
    createdBy: allUsers[4],
    createdAt: new Date("2025-11-07T16:45:00"),
    updatedAt: new Date("2025-11-09T09:15:00"),
    commentCount: 3,
    imageCount: 1,
  },
  {
    id: "3",
    issueNumber: 514,
    title: "Sound effects not playing in tutorial level",
    description: "All sound effects are muted in the tutorial...",
    status: "closed",
    priority: "low",
    category: "media",
    assignedTo: [allUsers[5]],
    createdBy: allUsers[6],
    createdAt: new Date("2025-11-06T11:20:00"),
    updatedAt: new Date("2025-11-08T15:30:00"),
    solvedCommit: "abc123",
    commentCount: 8,
    imageCount: 0,
  },
  {
    id: "4",
    issueNumber: 515,
    title: "Memory leak in main menu after extended play session",
    description: "Game crashes after 2+ hours of gameplay when returning to main menu...",
    status: "open",
    priority: "urgent",
    category: "dev",
    assignedTo: [allUsers[0], allUsers[3], allUsers[4]],
    createdBy: allUsers[1],
    createdAt: new Date("2025-11-09T08:00:00"),
    updatedAt: new Date("2025-11-10T11:30:00"),
    deadline: new Date("2025-11-12T00:00:00"),
    commentCount: 12,
    imageCount: 3,
  },
  {
    id: "5",
    issueNumber: 516,
    title: "UI scaling problem on ultrawide monitors",
    description: "Interface elements are stretched and misaligned on 21:9 displays...",
    status: "open",
    priority: "medium",
    category: "ui",
    assignedTo: [allUsers[2]],
    createdBy: allUsers[0],
    createdAt: new Date("2025-11-05T13:15:00"),
    updatedAt: new Date("2025-11-09T16:45:00"),
    commentCount: 2,
    imageCount: 2,
  },
];
